[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "2.0.0"
edition = "2024"
rust-version = "1.94.1"
license = "Apache-2.0"
repository = "https://github.com/vicondoa/d2b-client-toolkit"

[workspace.metadata.d2b-source]
repository = "https://github.com/vicondoa/d2b"
revision = "4018d9c9652bd826c2e6a9abccdcdcafb832d944"
distribution-fingerprint = "c2c99bdd77ba66948fce81161dcc3efde608eefefb96f28fa934c9f58d96d838"

[workspace.lints.clippy]
all = "warn"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
d2b-client = { git = "https://github.com/vicondoa/d2b", rev = "4018d9c9652bd826c2e6a9abccdcdcafb832d944", default-features = false }
d2b-contracts = { git = "https://github.com/vicondoa/d2b", rev = "4018d9c9652bd826c2e6a9abccdcdcafb832d944", default-features = false, features = ["v2-services"] }
d2b-session = { git = "https://github.com/vicondoa/d2b", rev = "4018d9c9652bd826c2e6a9abccdcdcafb832d944", default-features = false }
d2b-session-unix = { git = "https://github.com/vicondoa/d2b", rev = "4018d9c9652bd826c2e6a9abccdcdcafb832d944", default-features = false }
d2b-client-toolkit-colors = { path = "crates/d2b-client-toolkit-colors" }
d2b-client-toolkit-waybar = { path = "crates/d2b-client-toolkit-waybar" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", default-features = false }
