[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.76"
license = "Apache-2.0"
repository = "https://github.com/vicondoa/d2b-toolkit"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
d2b-toolkit-core = { path = "crates/d2b-toolkit-core" }
d2b-client = { path = "crates/d2b-client" }
d2b-wayland-core = { path = "crates/d2b-wayland-core" }
d2b-wayland-colors = { path = "crates/d2b-wayland-colors" }
d2b-wayland-proxy = { path = "crates/d2b-wayland-proxy" }
d2b-wayland-waybar = { path = "crates/d2b-wayland-waybar" }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "1"
